# https://docs.travis-ci.com/user/travis-lint

language: node_js

node_js:
  - stable

deploy:
  provider: npm
  email: vinhpq.tn@gmail.com
  api_key: e6309f85-6f7d-4458-9b96-52bb4f3c9ede
  on:
    all_branches: true